require_relative './craigslist_bikes/version'
require_relative './craigslist_bikes/cli'
require_relative './craigslist_bikes/bike'
require_relative './craigslist_bikes/search'
require_relative './craigslist_bikes/scraper'
require 'pry'
require 'nokogiri'
require 'open-uri'
